;;; term-sessions-tests.el --- Tests for term-sessions -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'term-sessions)

(ert-deftest term-sessions-test-attach-command-quotes-args ()
  (let ((term-sessions-zmx-program "zmx"))
    (should (equal (term-sessions--attach-command "dev" nil)
                   "zmx attach dev"))
    (should (equal (term-sessions--attach-command "dev box" "echo hello")
                   "zmx attach dev\\ box echo hello"))))

(ert-deftest term-sessions-test-zmx-list-names-parses-short-output ()
  (cl-letf (((symbol-function 'term-sessions--zmx)
             (lambda (&rest args)
               (should (equal args '("list" "--short")))
               " dev \n\nbuild\n")))
    (should (equal (term-sessions--zmx-list-names) '("dev" "build")))))

(ert-deftest term-sessions-test-active-p-uses-list ()
  (cl-letf (((symbol-function 'term-sessions--zmx-list-names)
             (lambda () '("dev" "build"))))
    (should (term-sessions--active-p "dev"))
    (should-not (term-sessions--active-p "missing"))))

(ert-deftest term-sessions-test-org-link-roundtrip-special-name ()
  (should (equal (term-sessions--org-link 'zmx "dev:box")
                 "term-session:zmx:local:dev%3Abox"))
  (should (equal (term-sessions--org-path-components "zmx:local:dev%3Abox")
                 '(:backend "zmx" :location "local" :target nil :name "dev:box"))))

(ert-deftest term-sessions-test-remote-org-link-roundtrip ()
  (let ((default-directory "/ssh:user@example:/tmp"))
    (should (equal (term-sessions--org-link 'zmx "dev:box")
                   "term-session:zmx:ssh:user%40example:dev%3Abox"))
    (should (equal (term-sessions--org-path-components
                    "zmx:ssh:user%40example:dev%3Abox")
                   '(:backend "zmx" :location "ssh" :target "user@example" :name "dev:box")))))

(ert-deftest term-sessions-test-org-path-opens-active-session ()
  (let (opened started)
    (cl-letf (((symbol-function 'term-sessions--active-p) (lambda (name) (equal name "dev")))
              ((symbol-function 'term-sessions-open) (lambda (name) (setq opened name)))
              ((symbol-function 'term-sessions-start) (lambda (name) (setq started name))))
      (term-sessions--open-org-path "zmx:local:dev" nil)
      (should (equal opened "dev"))
      (should-not started))))

(ert-deftest term-sessions-test-org-path-opens-ssh-with-remote-directory ()
  (let (active-directory opened-directory opened)
    (cl-letf (((symbol-function 'term-sessions--active-p)
               (lambda (name)
                 (setq active-directory default-directory)
                 (equal name "dev")))
              ((symbol-function 'term-sessions-open)
               (lambda (name)
                 (setq opened name)
                 (setq opened-directory default-directory))))
      (term-sessions--open-org-path "zmx:ssh:user%40example:dev" nil)
      (should (equal opened "dev"))
      (should (equal active-directory "/ssh:user@example:~/"))
      (should (equal opened-directory "/ssh:user@example:~/")))))

(ert-deftest term-sessions-test-org-path-offers-start-for-missing-session ()
  (let (opened started)
    (cl-letf (((symbol-function 'term-sessions--active-p) (lambda (_name) nil))
              ((symbol-function 'yes-or-no-p) (lambda (_prompt) t))
              ((symbol-function 'term-sessions-open) (lambda (name) (setq opened name)))
              ((symbol-function 'term-sessions-start) (lambda (name) (setq started name))))
      (term-sessions--open-org-path "zmx:local:missing" nil)
      (should-not opened)
      (should (equal started "missing")))))

(ert-deftest term-sessions-test-open-requires-existing-session ()
  (cl-letf (((symbol-function 'term-sessions--ensure-zmx) #'ignore)
            ((symbol-function 'term-sessions--active-p) (lambda (_name) nil)))
    (should-error (term-sessions-open-with-frontend "missing" nil 'term nil)
                  :type 'user-error)))

(ert-deftest term-sessions-test-start-allows-create ()
  (let (opened)
    (cl-letf (((symbol-function 'term-sessions--ensure-zmx) #'ignore)
              ((symbol-function 'term-sessions--ensure-interactive-attach-supported) #'ignore)
              ((symbol-function 'term-sessions--active-p) (lambda (_name) nil))
              ((symbol-function 'term-sessions--open-term)
               (lambda (name command buffer-name)
                 (setq opened (list name command buffer-name)))))
      (term-sessions-open-with-frontend "new" nil 'term t)
      (should (equal opened '("new" "zmx attach new" "*term-session:new*"))))))

(ert-deftest term-sessions-test-remote-open-dispatches-local-ssh-wrapper ()
  (let ((default-directory "/ssh:user@example:/tmp/project")
        (term-sessions-zmx-program "zmx")
        (term-sessions-ssh-program "ssh")
        opened)
    (cl-letf (((symbol-function 'term-sessions--ensure-zmx) #'ignore)
              ((symbol-function 'term-sessions--active-p) (lambda (_name) t))
              ((symbol-function 'term-sessions--open-term)
               (lambda (name command buffer-name)
                 (setq opened (list name command buffer-name default-directory)))))
      (term-sessions-open-with-frontend "dev" nil 'term nil)
      (should (equal (nth 0 opened) "dev"))
      (should (string-prefix-p "ssh user\\@example" (nth 1 opened)))
      (should (equal (nth 2 opened) "*term-session:dev*"))
      (should-not (file-remote-p (nth 3 opened))))))

(ert-deftest term-sessions-test-remote-interactive-attach-supports-ssh ()
  (let ((default-directory "/ssh:example:/tmp"))
    (should (equal (term-sessions--ensure-interactive-attach-supported)
                   '(:method "ssh" :user nil :host "example" :target "example" :localname "/tmp")))))

(ert-deftest term-sessions-test-remote-interactive-attach-refuses-unsupported-method ()
  (let ((default-directory "/sudo:example:/tmp"))
    (should-error (term-sessions--ensure-interactive-attach-supported)
                  :type 'user-error)))

(ert-deftest term-sessions-test-remote-ssh-attach-command ()
  (let ((default-directory "/ssh:user@example:/tmp/project")
        (term-sessions-zmx-program "zmx")
        (term-sessions-ssh-program "ssh"))
    (should (equal (term-sessions--interactive-attach-command "dev box")
                   "ssh user\\@example cd\\ /tmp/project\\ \\\&\\\&\\ zmx\\ attach\\ dev\\\\\\ box"))))

(ert-deftest term-sessions-test-term-buffer-base-name-has-no-stars ()
  (should (equal (term-sessions--term-buffer-base-name "dev")
                 "term-session:dev")))

(provide 'term-sessions-tests)
;;; term-sessions-tests.el ends here
